
# SEO settings
title: "Think"
title2: "space" # default: ""
description: "Just another minimalist Jekyll theme that focuses on technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://cdcarter.github.io/thinkspace # site url
baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/cdcarter/thinkspace
twitter_username: "cdcarter"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Christian Carter"
  job      : "Consultant"
  bio      : "queer af salesforce mvp."
  thumb    : /images/author.jpg
  email    : cdcarter@gmail.com
  url      : http://cdcarter.github.io
  github   : http://github.com/cdcarter
  twitter  : http://twitter.com/cdcarter

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@cdcarter"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
